### PR TITLE
move components

### PR DESCRIPTION
**Pull request by robert-czwartosz**
Hey, I've moved components to corresponding folders

### CODE REVIEW

**Review by skorpiom — APPROVED** [review]
Hey,
Great, seems to be divided correctly ;)

**Comment by skorpiom** [comment]
After looking further into that I wonder maybe it's good idea to add folders /pages/User and /Mentor
and actually /components/UserGrades should be in /pages/User - it's different page.

Pls let me know what you think ;)

**Comment by robert-czwartosz** [comment]
Good point!
Now it's corrected.

**Comment by kjreczek** [comment]
Looks good. 👍

**Pull request merged**
