### PR TITLE
Rc add button

### PR DESCRIPTION
**Pull request by robert-czwartosz**
Hey, I've created add button using material ui.

### CODE REVIEW

**Review by fszwedo — APPROVED** [review]
all looking good 👍

**Comment by skorpiom** [comment]
Hey, button looks nice, i would just change the color into #2196F3 , I think it's more in line with our design.

**Comment by robert-czwartosz** [comment]
@skorpiom  Thanks for suggestion, now button color is chaned :+1:

**Comment by skorpiom** [comment]
Great! ;)

**Review by skorpiom — APPROVED** [review]

**Pull request merged**
