### PR TITLE
Rc project setup

### PR DESCRIPTION
**Pull request by robert-czwartosz**
Project setup done.
I added sample controller and container configuration, but I don't know if it's correct.
To test sample controller run:
npm run start:dev
... and go to localhost:5000/hello/world
or localhost:5000/hello/world/your-name

### CODE REVIEW

**Comment by fszwedo** [comment]
Codewise I don't see anything to be changed, but I will still spend some time to check and understand the whole setup.
The only suggestion is to change the mongoose version to 5.11.15 as two console errors are not present there (there are some bugs in the newest mongoose version according to stackoverflow).
@robert-czwartosz

**Comment by robert-czwartosz** [comment]
Thanks 👍 Mongoose version changed!

**Review by fszwedo — APPROVED** [review]
all good for me 👍

**Review by kjreczek — APPROVED** [review]
I don't have any remarks. 👍

**Pull request merged**
