### PR TITLE
Fs team projects final

### PR DESCRIPTION
**Pull request by fszwedo**
merged both table view and edit view together, added an option to change the section for team project
to test just run npm start and go to "team project" tab

### CODE REVIEW

**Review by robert-czwartosz — COMMENTED** [review]
I suggest to implement add button next to search input.
This button will add empty team project, so it is not big problem.

Also there is padding to remove.
This code should fix it:
TeamProjects.tsx line 54
``` tsx
const Header = (detailedView: boolean) => {
    return detailedView ? <><h2>{HeaderText.EDIT}</h2></> : 
    (
    <>
        <h2>{HeaderText.MAIN}</h2>
        <SearchInput onSubmit={changeSearch} placeholder='Search for project name' />
    </>      
    )
  } 
```
line 78
``` tsx
return (
    <CssBaseline>
      <Paper className={styles.header} aria-label='TeamProjectsHeader'>
```

**Comment by skorpiom** [comment]
Hey,
works nice, there is only one problem, I updated FindSection component, and the new version is incompatible with the previous one. It's in the IP_ReferenceProjects branch and it works way better, but I don't know, how we wanna deal with it. Maybe after merging all things it will be good idea to update it?

Example implementation:
```

const [isOpenSectionsModal, setIsOpenSectionsModal] = useState(false);
 
 function closeSectionsModal() {
    setIsOpenSectionsModal(false)
  }

<FindSection
                isOpen={isOpenSectionsModal}
                handleClose={closeSectionsModal}
                onSectionSelection={handleSectionSelection}/>
```

**Review by skorpiom — APPROVED** [review]

**Comment by fszwedo** [comment]
@robert-czwartosz thanks for pointing that out - it's fixed
for add button - I'll try to do this in a separate pull, creating an empty project might be problematic as we don't have any place for putting mentor (and I'd like to think this through in general)

@skorpiom I'll do it after all the merges will be done then

@robert-czwartosz can we merge this in this state for now?

**Review by robert-czwartosz — APPROVED** [review]

**Comment by robert-czwartosz** [comment]
@fszwedo feel free to merge after resolving the conflict

**Pull request merged**
