### PR TITLE
KR team endpoints

### PR DESCRIPTION
**Pull request by kjreczek**
Added endpoints for team and tests, they seem to work. Please check if it's correct.

get - **/teams** - get teams list
get - **/teams/:id** - get team by id
post - **/teams** - create team
delete - **/teams/:id** - delete team
patch - **/teams/:id** - update team
post - **/teams/:id/users** - add user to team
delete - **/teams/:teamId/users/:userId** - delete user from team
post - **/teams/:id/mentor** - add mentor to team
delete - **/teams/:id/mentor/** - delete mentor from team

### CODE REVIEW

**Comment by kjreczek** [comment]
@JustynaSmoliga @fszwedo pull is ready to review, I changed everything I had 😃

**Review by fszwedo — APPROVED** [review]
looks ok to me

**Review by JustynaSmoliga — COMMENTED** [review]
Code looks good and endpoints work fine. I wonder, if update team endpoint is necessary, because all team fields (mentor and users) have their own endpoints. What do you think?

**Comment by kjreczek** [comment]
> Code looks good and endpoints work fine. I wonder, if update team endpoint is necessary, because all team fields (mentor and users) have their own endpoints. What do you think?

I assumed that if someone wants to update users and mentors at the same time, then they can do that this way. :P

**Review by JustynaSmoliga — APPROVED** [review]

**Pull request merged**
