### PR TITLE
FS Registration Mail

### PR DESCRIPTION
**Pull request by fszwedo**
added a welcome email sending to the registration process - email should be sent once you register a new user (you can check it by just registering a user with your email)

also adjusted a bit the email template, it's now used by both password reset and welcome emails (nothing super fancy but looks better than it used to)

### CODE REVIEW

**Comment by kjreczek** [comment]
I tested it and didn't receive any email, is this working with some other pulls that are not merged? Is there some extra config required?

**Review by kjreczek — COMMENTED** [review]
I tested it and didn't receive any email, is this working with some other pulls that are not merged? Is there some extra config required?

**Comment by fszwedo** [comment]
@JustynaSmoliga @kjreczek when you check http://localhost:5000/api/users/register the email is not being sent to you? 
{
"username": "test",
"name": "test",
"surname": "testtest",
"email": "**your mail**",
"type": "1",
"password": "kotlet"
}
It works just fine for me locally, don't see any obvious reasons for this not to work

**Review by JustynaSmoliga — APPROVED** [review]
Everything works fine, mail message looks very good ;) I haven't any suggestions.

**Comment by robert-czwartosz** [comment]
There are two registration endpoints:
/api/user/register and /api/register
Registration using both endpoints should cause sending email notification.

**Review by kjreczek — APPROVED** [review]
Now it works and looks good 👍

**Pull request merged**
